name: Check Quality Gates
runs:
  using: "composite"
  steps:
    - name: Install UI-Test prerequisites
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    - name: Run Gradle Tasks
      shell: bash
      # TODO jacocoTestReport and enforce threshold
      run: xvfb-run -a -s "-screen 0 1280x1024x24" ./gradlew detekt jacocoTestReport check --console=plain
    - name: Validate Documentation # TODO should run independent from previous step, so both can fail simultaneously
      shell: bash
      run: ./bin/validate_documentation.sh
