name: Execute Quality Gate
runs:
  using: "composite"
  steps:
    - name: Install UiTest prerequisites
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    - name: Run Gradle Tasks
      shell: bash
      run: xvfb-run -a -s "-screen 0 1280x1024x24" ./gradlew detekt jacocoTestReport check --console=plain
    - name: Validate Documentation
      shell: bash
      run: ./bin/validate_documentation.sh
